road_half_len = 16;    % 每条路向外延伸长度
lane_width    = 3.0;  % 单车道宽度
lane_offset   = lane_width/2;
hwid_intersection = 2*lane_width/(2-sqrt(2));

% figure;
hold on;
axis equal;

xlim([-road_half_len road_half_len]);
ylim([-road_half_len road_half_len]);

road_color = [0.15 0.15 0.15];

% 东西向道路
rectangle( ...
    'Position', ...
    [-road_half_len, -lane_width, 2*road_half_len, 2*lane_width], ...
    'FaceColor', road_color, 'EdgeColor', 'none' ...
);

% 南北向道路
rectangle( ...
    'Position', [-lane_width, -road_half_len, 2*lane_width, ...
    2*road_half_len], 'FaceColor', road_color, 'EdgeColor', 'none' ...
);

line_style = '--';
lw = 1.2;

% 南侧路口起始线
plot( ...
    [-lane_width lane_width], [-hwid_intersection -hwid_intersection], 'w', 'LineStyle', ...
    line_style, 'LineWidth', lw ...
);

% 北侧路口起始线
plot( ...
    [-lane_width lane_width], [hwid_intersection hwid_intersection], 'w', 'LineStyle', ...
    line_style, 'LineWidth', lw ...
);

% 西侧路口起始线
plot( ...
    [-hwid_intersection -hwid_intersection], [-lane_width lane_width], 'w', 'LineStyle', ...
    line_style, 'LineWidth', lw ...
);

% 东侧路口起始线
plot( ...
    [hwid_intersection hwid_intersection], [-lane_width lane_width], 'w', 'LineStyle', ...
    line_style, 'LineWidth', lw ...
);

% 东西向中心线
plot( ...
    [-road_half_len -hwid_intersection], [0 0], 'w', 'LineStyle', ...
    line_style, 'LineWidth', lw ...
);

plot( ...
    [hwid_intersection road_half_len], [0 0], 'w', 'LineStyle', ...
    line_style, 'LineWidth', lw ...
);

% 南北向中心线
plot( ...
    [0 0], [-road_half_len -hwid_intersection], 'w', 'LineStyle', ...
    line_style, 'LineWidth', lw ...
);

plot( ...
    [0 0], [hwid_intersection road_half_len], 'w', 'LineStyle', ...
    line_style, 'LineWidth', lw ...
);

set(gca,'XTick',[],'YTick',[]);
box on;
title( ...
    'Four-way intersection with bidirectional lanes (right-hand traffic)' ...
);
